import { PrismaClient } from "./generated/index.js";

const prisma = new PrismaClient();

async function main() {
  // Reward history is intentionally left empty; rewards are generated on demand.
  console.log("reward-service seed: nothing to do (rewards are generated by the service).");
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
