apiVersion: v1
kind: Service
metadata:
  name: reward-service
  labels:
    app.kubernetes.io/name: reward-service
    app.kubernetes.io/part-of: tasktreat
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: reward-service
  ports:
    - name: http
      port: 4003
      targetPort: 4003
      protocol: TCP
